# Generated by Django 4.2 on 2023-05-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('idfunc', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('regfuncional', models.CharField(max_length=12)),
                ('datanasc', models.DateField()),
                ('doc', models.CharField(max_length=12)),
                ('senha', models.CharField(max_length=15)),
            ],
        ),
    ]
