# Generated by Django 4.2 on 2023-05-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criarConta', '0002_funcionario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='doc',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
