# Generated by Django 4.2 on 2023-05-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criarConta', '0004_remove_funcionario_datanasc'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='password',
            field=models.CharField(default=0, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
