# Generated by Django 4.2 on 2023-05-22 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        
=======
        ('criarConta', '0004_remove_funcionario_datanasc'),
>>>>>>> 6fc9a8ee62cef2fd5ef5db37afcb608da0febef4
    ]

    operations = [
        migrations.CreateModel(
            name='DadosMedicos',
            fields=[
                ('iddadosmed', models.AutoField(primary_key=True, serialize=False)),
                ('tpsanguineo', models.CharField(blank=True, max_length=2, null=True)),
                ('convenio', models.CharField(blank=True, max_length=100, null=True)),
                ('usamedicamento', models.CharField(blank=True, max_length=100, null=True)),
                ('possuialergia', models.CharField(blank=True, max_length=100, null=True)),
                ('restricaoativ', models.CharField(blank=True, max_length=100, null=True)),
                ('problemasaude', models.CharField(blank=True, max_length=100, null=True)),
                ('possuilesao', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('eol', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('nomesocial', models.CharField(blank=True, max_length=100, null=True)),
                ('raca', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('datanasc', models.DateField(blank=True, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('certidao', models.CharField(blank=True, max_length=10, null=True)),
                ('folha', models.CharField(blank=True, max_length=10, null=True)),
                ('livro', models.CharField(blank=True, max_length=10, null=True)),
                ('rg', models.CharField(blank=True, max_length=27, null=True)),
                ('dataexp', models.DateField(blank=True, null=True)),
                ('nomemae', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('numendereco', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=10, null=True)),
                ('tel', models.CharField(blank=True, max_length=15, null=True)),
                ('telrecado', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='fotos_usuarios/')),
                ('fotodoc', models.ImageField(blank=True, upload_to='fotos_doc/')),
                ('fotodocresp', models.ImageField(blank=True, upload_to='fotos_doc/')),
                ('iddadosmed', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='cadastroUsuario.dadosmedicos')),
                ('idfunc', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='criarConta.funcionario')),
            ],
        ),
    ]
