# Generated by Django 4.2 on 2023-05-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('numcadastro', models.IntegerField(blank=True, null=True)),
                ('eol', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('nomesocial', models.CharField(blank=True, max_length=100, null=True)),
                ('raca', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('datanasc', models.DateField(blank=True, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('certidao', models.CharField(blank=True, max_length=10, null=True)),
                ('folha', models.CharField(blank=True, max_length=10, null=True)),
                ('livro', models.CharField(blank=True, max_length=10, null=True)),
                ('rg', models.CharField(blank=True, max_length=27, null=True)),
                ('dataexp', models.DateField(blank=True, null=True)),
                ('nomemae', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('numendereco', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=10, null=True)),
                ('tel', models.CharField(blank=True, max_length=15, null=True)),
                ('telrecado', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='fotos_usuarios/')),
                ('fotodoc', models.ImageField(blank=True, upload_to='fotos_doc/')),
                ('fotodocresp', models.ImageField(blank=True, upload_to='fotos_doc/')),
                ('tpsanguineo', models.CharField(blank=True, max_length=2, null=True)),
                ('convenio', models.CharField(blank=True, max_length=100, null=True)),
                ('usamedicamento', models.CharField(blank=True, max_length=100, null=True)),
                ('possuialergia', models.CharField(blank=True, max_length=100, null=True)),
                ('restricaoativ', models.CharField(blank=True, max_length=100, null=True)),
                ('problemasaude', models.CharField(blank=True, max_length=100, null=True)),
                ('possuilesao', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
