# Generated by Django 4.2 on 2023-05-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroUsuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='numcadastro',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
