# Generated by Django 4.2 on 2023-05-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroUsuario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nespecial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
