# Generated by Django 4.2 on 2023-05-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroUsuario', '0003_usuario_nespecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nomerecado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
