# Generated by Django 4.2 on 2023-05-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroUsuario', '0005_usuario_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='eol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idade',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numcadastro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
