<<<<<<< HEAD
# Generated by Django 4.2 on 2023-05-25 18:06

from django.db import migrations, models
import django.contrib.auth.models
=======
# Generated by Django 4.2 on 2023-05-20 15:43

from django.db import migrations, models
>>>>>>> 6fc9a8ee62cef2fd5ef5db37afcb608da0febef4


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
     
=======
>>>>>>> 6fc9a8ee62cef2fd5ef5db37afcb608da0febef4
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
<<<<<<< HEAD
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('idfunc', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('regfuncional', models.CharField(max_length=12)),
                ('doc', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    
=======
                ('idfunc', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('regfuncional', models.CharField(max_length=12)),
                ('datanasc', models.DateField()),
                ('doc', models.CharField(max_length=12)),
                ('senha', models.CharField(max_length=15)),
            ],
        ),
>>>>>>> 6fc9a8ee62cef2fd5ef5db37afcb608da0febef4
    ]
