# Generated by Django 4.2 on 2023-05-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criarConta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(default='cbsl@live.com', max_length=100),
        ),
    ]
