from django.db import models
from criarConta.models import Funcionario

class Usuario(models.Model):
    idusuario = models.AutoField(primary_key=True)
    numcadastro= models.CharField(max_length=20, null=True, blank=True)
    idfunc = models.ForeignKey(Funcionario, on_delete=models.PROTECT, editable=False) #chave estrangeira
    eol = models.CharField(max_length=20, null=True, blank=True)
    nome = models.CharField(max_length=100, null=True, blank=True)
    nomesocial = models.CharField(max_length=100, null=True, blank=True)
    raca = models.CharField(max_length=20, null=True, blank=True)
    cidade = models.CharField(max_length=100, null=True, blank=True)
    uf = models.CharField(max_length=2, null=True, blank=True)
    datanasc = models.DateField(null=True, blank=True)
    idade = models.CharField(max_length=3, null=True, blank=True)
    certidao = models.CharField(max_length=10, null=True, blank=True)
    folha = models.CharField(max_length=10, null=True, blank=True)
    livro = models.CharField(max_length=10, null=True, blank=True)
    rg = models.CharField(max_length=27, null=True, blank=True)
    dataexp = models.DateField(null=True, blank=True)
    nomemae = models.CharField(max_length=100, null=True, blank=True)
    endereco = models.CharField(max_length=100, null=True, blank=True)
    nespecial =  models.CharField(max_length=255, null=True, blank=True)
    numendereco = models.CharField(max_length=10, null=True, blank=True)
    complemento = models.CharField(max_length=10, null=True, blank=True)
    cep = models.CharField(max_length=9, null=True, blank=True)
    tel = models.CharField(max_length=15, null=True, blank=True)
    telrecado = models.CharField(max_length=15, null=True, blank=True)
    nomerecado = models.CharField(max_length=100, null=True, blank=True)
    celular = models.CharField(max_length=15, null=True, blank=True)
    foto = models.ImageField(upload_to='fotos_usuarios/', blank=True)
    fotodoc = models.ImageField(upload_to = 'fotos_doc/', blank=True)
    fotodocresp = models.ImageField(upload_to = 'fotos_doc/', blank=True)
    tpsanguineo = models.CharField(max_length=2, null=True, blank=True)
    convenio = models.CharField(max_length=100, null=True, blank=True)
    usamedicamento = models.CharField(max_length=100, null=True, blank=True)
    possuialergia = models.CharField(max_length=100, null=True, blank=True)
    restricaoativ = models.CharField(max_length=100, null=True, blank=True)
    problemasaude = models.CharField(max_length=100, null=True, blank=True)
    possuilesao = models.CharField(max_length=100, null=True, blank=True)
